name: Publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout v3
        uses: actions/checkout@v3

      - name: Login in Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-explorer:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-explorer:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to GitHub Pages
        run: |
          docker run -v ${{ github.workspace }}:/app ${{ secrets.DOCKER_USERNAME }}/docker-explorer:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}